/* builtin.h -- the game that ships inside the emulator, generated by
   tools/mkrom.c and linked in, so that ./gameboy needs no rom at all */
#ifndef GB_BUILTIN_H
#define GB_BUILTIN_H

extern const unsigned char builtin_rom[];
extern const unsigned long builtin_rom_size;

#endif
